# Ansible Inventory for Mailcow Setup

mailserver:
  hosts:
    mailserver1:
      ansible_host: "{{ target_server_ip | default('localhost') }}"
      ansible_user: "{{ ansible_ssh_user | default('root') }}"
      ansible_ssh_private_key_file: "{{ ssh_key_path | default('~/.ssh/id_rsa') }}"
      
      # Server specific variables
      mail_server_name: "{{ mail_domain_name }}"
      admin_email_address: "{{ admin_email }}"
